### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by alexfr26** [noggatur/portfolio#1]
```EXCEPTION: Error in ./SiteComponent class SiteComponent - inline template:12:2 caused by: $ is not defined```

**Comment by noggatur** [comment]
`ng -v`?

**Comment by alexfr26** [comment]
@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.10

**Comment by alexfr26** [comment]
The problem was caused by _QueryRotateCompressed_ plugin absence in the "Plugins" directory. Solved the problem by adding it manually.

**Comment by noggatur** [comment]
@alexfr26 removed plugins folder from `.gitignore`
